title: 2020 1 OSS Project 
email: one0955@naver.com
author:
  picture: http://site.hugocarreira.me/assets/img/compressed/hugo.jpg #URL FORMAT
  name: Kim Gwang Won
  location: Korea
  description: "21 years old, studying computer science"  
description: Kim Gwang Won 2019312751

remote_theme : hugocarreira/jekyll-vision-casper-theme

baseurl: 
url: https://one0955.github.io/casper
twitter_username: one0955
github_username: one0955
github_url: https://one0955.github.io/casper

# Build settings
permalink: :title
paginate: 1
paginate_path: "page:num"
kramdown:
  input: GFM
  hard_wrap: false
highlighter: rouge
gems:
  - jekyll-feed
  - jekyll-paginate
exclude:
  - Gemfile
  - Gemfile.lock
